sudo: required
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-python-dev libboost-all-dev systemtap-sdt-dev libfuzzy-dev graphviz
install:
  - sudo pip install pylibemu
  - pip install tox
script:
  - echo "/opt/libemu/lib/" | sudo tee --append /etc/ld.so.conf.d/libemu.conf
  - sudo ldconfig
  - sudo mkdir -p /etc/thug/{rules,personalities,scripts}
  - sudo cp -R thug/Classifier/rules/* /etc/thug/rules/
  - sudo cp -R thug/DOM/personalities/* /etc/thug/personalities
  - sudo cp -t /etc/thug/scripts thug/DOM/{thug.js,storage.js,date.js} thug/Debugger/d8.js
  - sudo cp -t /etc/thug/ conf/thug.conf
  - tox
  - echo "Build done"
